### ISSUE TITLE
RSS/atom feed not working

### ISSUE THREAD

**Issue by julianrichen** [bravo-kernel/bravo-kernel.github.io#5]
Hello,
I follow your blog at http://www.bravo-kernel.com, noticed that I was no longer getting the RSS feed. Seems like it's returning a 404:
http://www.bravo-kernel.com/atom.xml

**Comment by bravo-kernel** [comment]
Thank you kindly for reporting mr. @julianrichen. It seems the feed-generator plugin went missing after a re-install. Re-added https://github.com/hexojs/hexo-generator-feed.
